imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [SymfonyCmfSimpleCmsBundle, SymfonyCmfCreateBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #lessphp:
            #file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            #apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        path:     %database_path%
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en:
                - en
                - de
            de:
                - de
                - en

liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

symfony_cmf_routing_extra:
    dynamic:
        enabled: true

symfony_cmf_simple_cms:
    routing:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Document\Page:  SymfonyCmfSimpleCmsBundle:Page:index.html.twig
    multilang:
        locales: %locales%
    use_sonata_admin: false

knp_menu:
    twig: true

symfony_cmf_menu:
    use_sonata_admin: false
    menu_basepath: /cms

symfony_cmf_create:
    phpcr_odm: true

lunetics_locale:
    strict_mode: true
    guessing_order:
        - cookie
        - router
        - browser
    allowed_locales: %locales%